# Generated by Django 5.0.7 on 2024-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="search_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
